package(default_visibility = ["//visibility:public"])

cc_library(
    name = "kd_tree",
    srcs = [
        "kd_tree.cc",
        "kd_tree.h",
    ],
)

cc_binary(
    name = "kd_tree_test",
    srcs = [
        "kd_tree.cc",
        "kd_tree.h",
        "kd_tree_test.cc",
    ],
)
