package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = [
        "frame.h",
        "para.h",
        "status.h",
        "utils.h",
        "vehicle_config.h",
    ],
)
